version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1202
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: 1202
    ports:
      - "3307:3306"
    networks:
      - ecommerce-network

  springboot-app:
    build: .
    container_name: springboot_container
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Niraj123
    ports:
      - "9090:8080"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
